# 공통
spring.application.name=matmatgotgot
#server port
server.port=9999
#mysql settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/matgotdb?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=2222
#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.twotwo.matmatgotgot.domain.*
mybatis.configuration.jdbc-type-for-null=NULL										
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30
#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tkavkf30409
spring.mail.password=mstwpaxeiwmoefah
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
#jwt settings
jwt.secret=TYrOXTb1km6R4x1lGndgp11pgw4Fn6P+y1Lm2Qf0qIc=
jwt.expiration=3600000
#file upload settings
spring.servlet.multipart.max-file-size=10MB										
spring.servlet.multipart.max-request-size=50MB										
file.root=C:/Temp/upload/web/matgot/
# Google OAuth2 Client Settings
spring.security.oauth2.client.registration.google.client-id=648568970946-ifvq25nvtsg8np7c1984euvl65937a42.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173/login/oauth2/code/google
# CLOVA OCR
clova.ocr.secret-key=RGZDZUxvSllWTElSS0tqY1p4aXpVaUFvZEhGS0hpT0o=
clova.ocr.api-url=https://v9fq4rfs23.apigw.ntruss.com/custom/v1/53517/9a686bb414feb410b2f67a0671507b7e4e4e99da022e2635e2bb9eb487ee8a68/document/receipt

spring.config.import=optional:application-secret.properties
# NAVER API - jiyeon
naver.client-id=q7D6tEw3nQUevtuMU9zQ
naver.secret=P2ZaXWvJ2j

# NAVER KEY - kgy
naver.client.id.k=Py1IXbnWwRHfSTIqQYsS		
naver.client.secret.k=D5Me7x98ut		