# 공통
spring.application.name=matmatgotgot
spring.profiles.active=secret

#server port
server.port=

#mysql settings
spring.datasource.driver-class-name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=
mybatis.mapper-locations=
mybatis.type-aliases-package=
mybatis.configuration.jdbc-type-for-null=
mybatis.configuration.default-fetch-size=
mybatis.configuration.default-statement-timeout=

#email settings
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.starttls.required=
spring.mail.properties.mail.smtp.auth=

#jwt settings
jwt.secret=
jwt.expiration=

#file upload settings
spring.servlet.multipart.max-file-size=
spring.servlet.multipart.max-request-size=
file.root=

# Google OAuth2 Client Settings
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.redirect-uri=

# CLOVA OCR
clova.ocr.secret-key=
clova.ocr.api-url=

# NAVER API
naver.client-id=
naver.secret=