spring.application.name=matmatgotgot_back

#server port
server.port=8888

#oracle settings
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=TEAM1_DB
spring.datasource.password=1111

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tkavkf30409
spring.mail.password=wshognsmtmopuaxh
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true

#jwt settings
jwt.secret-key=abcdefghijklmnopqrstuvwxyz12345678901234567890
jwt.expire-hour=1


#file upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB